### ISSUE TITLE
다수의 폰트를 다운 받는다.

### ISSUE THREAD

**Issue by polmki123** [polmki123/SONMAT_DEEP#1]
목표 : 문장 데이터셋을 위한 다수의 폰트를 다운 받는다.

1. 인터넷을 통해 다양한 폰트를 다운 받는다.
2. 다운 받은 폰트를 구글 드라이브에 저장한다.

티켓 종료
다양한 폰트를 다운 받아 공용 구글 드라이브에 저장한다.

**Comment by polmki123** [comment]
![default](https://user-images.githubusercontent.com/28795477/47447110-c06c0a00-d7f7-11e8-93b4-d061b133e9a5.png)
글자가 다른 크기인 문장을 완성하였다.

**Comment by ssunhye** [comment]
글자 폰트 랜덤값으로 바꿔주었습니다.
