### ISSUE TITLE
흐릿한 글자의 문장을 jpg로 만드는 코드 생성

### ISSUE THREAD

**Issue by ssunhye** [polmki123/SONMAT_DEEP#11]
목표 : 흐릿한 문장을 jpg로 저장한다.

1. 각각의 글자 이미지를 흐릿하게 만든다.
3. 각각의 글자를 흐릿하게 만든 문장을 jpg로 저장한다.

티켓 종료 조건
흐릿하게 만들어진 문장의 jpg 파일 생성

**Comment by polmki123** [comment]
![image](https://user-images.githubusercontent.com/28795477/47889761-ef851a00-de8e-11e8-9dec-8d4b034807a9.png)
opencv를 이용하여 코드 작성 완료
