### ISSUE TITLE
글자에 랜덤으로 흐릿함을 준 문장을 jpg로 저장하는 코드 생성

### ISSUE THREAD

**Issue by ssunhye** [polmki123/SONMAT_DEEP#12]
목표 : 글자를 흐릿하게 시킨 정도가 랜덤으로 적용되는 문장이 jpg 파일로 만들어 진다.

1. 각각의 글자에 적용된 흐릿한 정도를 랜덤으로 적용.
2. 흐릿한 문장을 jpg 로 저장

티켓 종료 조건
글자의 흐릿한 정도가 랜덤인 문장의 jpg 파일 생성.

**Comment by polmki123** [comment]
![image](https://user-images.githubusercontent.com/28795477/47889761-ef851a00-de8e-11e8-9dec-8d4b034807a9.png)
opencv를 이용하여 코드 작성 완료
