### ISSUE TITLE
시험 학습 구동 및 결과 산정

### ISSUE THREAD

**Issue by willshawn** [polmki123/SONMAT_DEEP#32]

**Comment by polmki123** [comment]
![3my](https://user-images.githubusercontent.com/28795477/48888607-99e0d380-ee76-11e8-9a24-b7c01da6112b.jpg)
![4my](https://user-images.githubusercontent.com/28795477/48888610-9b120080-ee76-11e8-8994-ebd84d9a254d.jpg)
![5my](https://user-images.githubusercontent.com/28795477/48888611-9b120080-ee76-11e8-8f40-a49c61da3e8b.jpg)
![1my](https://user-images.githubusercontent.com/28795477/48888613-9baa9700-ee76-11e8-8406-7c23fa5232c8.jpg)
![2my](https://user-images.githubusercontent.com/28795477/48888614-9baa9700-ee76-11e8-9c8e-2ed9ce95eb84.jpg)
좋지 않은 결과 출력
